### ISSUE TITLE
Does the demo support more precise measurement

### ISSUE THREAD

**Issue by xiuqijix** [intel/websensor-compass#4]
I test the Complementary/Magnetometer/Accelerometer/Gyroscope, only get the results of the Angles of 0/90/180/270 degrees. Does the demo support more precise measurement and how can I get them？

**Comment by kenchris** [comment]
Yes it is supposed to support any kind of angles, like 27 or 128... by default.

It used to work, but of course the spec and implementation keeps changing so things might have broken

**Comment by kenchris** [comment]
Here is a video of it: https://www.youtube.com/watch?v=RLDwkLPU42Y

**Comment by kenchris** [comment]
I still see code like this:

```
  setFromSensorData(gravity, geomagnetic) {
    let Ax = gravity.accelerationX;
    let Ay = gravity.accelerationY;
    let Az = gravity.accelerationZ;

    let Ex = geomagnetic.magneticFieldX;
    let Ey = geomagnetic.magneticFieldY;
    let Ez = geomagnetic.magneticFieldZ;
```

I believe these changed as well. ie accelerationX is not just x

**Comment by xiuqijix** [comment]
The issue is not reproduce, so close it.
