### ISSUE TITLE
Consider making OrientationMatrix use the new Geometry Interfaces

### ISSUE THREAD

**Issue by kenchris** [intel/websensor-compass#5]
This is now in Chrome Canary, so as we already depend on that, we can start using this: https://drafts.fxtf.org/geometry/

**Comment by xiuqijix** [comment]
Firefox support DOMMatrix, but maybe chrome not. Run the demo has an error "Uncaught ReferenceError: DOMMatrix is not defined". How can I run it on chrome.

**Comment by kenchris** [comment]
Try turning on Experimental Web Platform features in about:flags. Works in Chrome for me

**Comment by xiuqijix** [comment]
Thanks, it works.

**Comment by kenchris** [comment]
I added a polyfill so this shouldn't be needed, but there seems to be a bug - but I haven't been able to find it, so any help is welcome :-)

**Comment by xiuqijix** [comment]
Yeah, I see the bug and I will try to find it out.
