### ISSUE TITLE
Accelerometer has wrong value use the newest code.

### ISSUE THREAD

**Issue by xiuqijix** [intel/websensor-compass#7]
I test the Accelerometer, only get the results of the Angles of 0/354-359 degrees.

**Comment by kenchris** [comment]
with out without Experimental Web Platform features flag?

**Comment by xiuqijix** [comment]
The Experimental Web Platform features flag Enable or Disable are both have the issue.

**Comment by kenchris** [comment]
Strange, works fine for me, with ?filter=a

**Comment by kenchris** [comment]
Can this be closed?

**Comment by xiuqijix** [comment]
The issue is not reproduce, so close it.
